name: up_reps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  google_fonts: ^3.0.1
  carousel_pro_nullsafety: ^1.0.2
  intl: ^0.17.0
  carousel_slider: ^4.1.1
  splashscreen: ^1.3.5
  flare_flutter: ^3.0.2
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  flutter_svg: ^1.1.6
  favorite_button: ^0.0.4
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon/android/res/mipmap-xxxhdpi/ic_launcher.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: BodoAmatic
      fonts:
        - asset: fonts/BodoAmat.ttf
  #     
    - family: Pulang
      fonts:
        - asset: fonts/Pulang.ttf

    - family: StoryElement
      fonts:
        - asset: fonts/StoryElementRegular.ttf